2023 Washington Court House....
911 CALL ×××-606>>4887>>>
Female possibility ^^422>>7
Unresponsive 

Naloxone 12m 0000..8:28pm.0000
136 Rawlings Street ^^^>>

Overdose ^^ age 22 f w 
CfS command log 
911 Call identity M Ethan Johnson^^^ Railroad >>48. JEFFERSONVILLE 
JANUARY 17>><2023>>>


Detty Andrea^^^2022
MORRIS Kristin ^^^^Downing  Dorraine ^^ 

Patient  Refused 

Erin ^^^Lawson^^^

Randy ^^^Nicole
